REST API for Emender-Jenkins interface
======================================
:icons: font
Pavel Tišnovský <ptisnovs@redhat.com>
v1.0, 2016-06-15

Emender-Jenkins Interface is controlled exclusively via REST API.
Basic supported operations:

Jobs CRUD:

* create new job (that calls Emender using its build script)
* read job config
* update job (reconfigure)
* delete job

Other job-related calls:

* start job
* enable job
* disable job
* get list of all jobs
* get job results

Other calls:

* get info about the application
* get banner


REST API calls
--------------



Info
~~~~

    /api

Gets information about the app, such as the version currently running.

Method: +GET+

Content-Type: +application/json+

Example: +curl http://url-to-interface:port/api+

Response:

[source,json]
----
{
    "name" : "Emender Jenkins Service",
    "version" : "0.1.0",
    "api_prefix" : "/api",
    "hostname" : "hostname"
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+



Show configuration
~~~~~~~~~~~~~~~~~~

    /api/configuration

Gets information about the current configuration.

Method: +GET+

Content-Type: +application/json+

Example: +curl http://url-to-interface:port/api/configuration+

Response:

[source,json]
----
{
    "info":
    {
        "version":"0.1.0"
    },
    "jenkins":{
        "jenkins-url":"https:\/\/10.20.30.40\/",
        "jenkins-job-prefix-url":"job\/",
        "jenkins-job-list-url":"foobar",
        "jenkins-auth":""
    },
    "jobs":
    {
        "test-jobs-suffix":"(test)"
    },
    "config":
    {
        "verbose":true,
        "pretty-print":true
    },
    "api":
    {
        "prefix":"\/api"
    },
    "fetcher":
    {
        "delay":"10"
    }
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+



Banner
~~~~~~

    api/system/banners

Gets the banners that should be displayed in the UI.

Method: +GET+

Content­Type: +application/json+

Example: +curl http://url-to-interface:port/api/system/banners+

Response:

[source,json]
----
[ 
    { 
        "message": "Alpha version",
        "type": "warning" 
    } 
] 
----

HTTP Status Code:
+HTTP/1.1 200 OK+



Create new job
~~~~~~~~~~~~~~

    /api/create_job

Creates new jenkins job

Method: +POST+

Content­Type: +application/json+

Post Data (minimal version):

[source,json]
----
{
    "ssh_url_to_repo" : "git@some:repo.git",
    "name"            : "jobName (test)",
    "branch"          : "preview"
} 
----

Post Data (max. version):

[source,json]
----
{
    "ssh_url_to_repo" : "git@some:repo.git",
    "name"            : "jobName (test)",
    "branch"          : "preview",
    "metadata": {
        "product": "product name",
        "version": "product version",
        "language": "en­US",
        "environment": "preview",
        "content_directory": "Book directory",
        "content_type": "book"
    } 
} 
----

Response:

[source,json]
----
{
    "status"   : "ok",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "create",
    "jenkins-response":{ "status":200, ...}
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "create",
    "message"  : "Job already exist"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "create",
    "message"  : "invalid input"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Delete job
~~~~~~~~~~

    /api/delete_job

Deletes an existing Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

Response:

[source,json]
----
{
    "status"   : "ok",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "doDelete",
    "jenkins-response":{"status":302...}}
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "delete",
    "message"  : "Job does not exist"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Get job
~~~~~~~

    /api/get_job/{JOB_NAME}

Method: +GET+

Content-Type: +application/json+

Response:

[source,json]
----
{
    "job-name:    "doc-${PRODUCT}-${VERSION}-${BOOK-NAME}-${LANGUAGE} (test)",
    "product":    "${PRODUCT}
    "version":    "${VERSION}
    "book-name":  "${BOOK-NAME}",
    "job-status": "ok/unstable/failure/disabled",
    "test-summary": {
        "message:": "Total: 7  Passed: 5  Failed: 2",
        "results": {"total":7,"passed":5,"failed":2}
    }
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "unknown-job",
    "command"  : "get-job",
    "message"  : "Job does not exis"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Update job
~~~~~~~~~~
    /api/update_job

Updates an existing Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data (minimal version):

[source,json]
----
{
    "name"            : "doc-${PRODUCT}-${VERSION}-${BOOK-NAME}-${LANGUAGE} (test)",
    "ssh_url_to_repo" : "git@some:repo.git",
    "branch"          : "preview"
} 
----

Post Data (max. version): 

[source,json]
----
{
    "name"            : "doc-${PRODUCT}-${VERSION}-${BOOK-NAME}-${LANGUAGE} (test)",
    "ssh_url_to_repo" : "git@some:repo.git",
    "branch"          : "preview"
    "metadata": {
        "product": "product name",
        "version": "product version",
        "language": "en­US",
        "environment": "preview",
        "content_directory": "Book directory",
        "content_type": "book"
    } 
}
----

Response:

[source,json]
----
{
    "status":"ok",
    "job-name":"doc-Test_Product-1.0-Test_Book-en-US (test-preview)",
    "command":"update",
    "jenkins-response":
    {
        "status":200,
        "headers":
        {
            "Date":"Thu, 11 Aug 2016 10:08:38 GMT",
            "X-Content-Type-Options":"nosniff",
            "Connection":"close",
            "Server":"Jetty(9.2.z-SNAPSHOT)"
        },
        "body":"",
        "request-time":86,
        "trace-redirects": ["http:\/\/10.34.3.139:8080\/job\/doc-Test_Product-1.0-Test_Book-en-US%20(test-preview)\/config.xml"],
        "orig-content-encoding":null
    }
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "not set!",
    "command"  : "update",
    "message"  : "invalid input"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Get jobs
~~~~~~~~

    /api/get_jobs
    /api/get_jobs?product=PRODUCT-NAME
    /api/get_jobs?product=PRODCUT-NAME&version=VERSION

Get list of job statuses. This list can be filtered for given product or product+version.

Method: +GET+

Content-Type: +application/json+

Example: +curl http://url-to-interface:port/api/system/banners+
curl -X GET -v localhost:3000/api/get_jobs?product=TEST%20PRODUCT\&version=1

Response:

[source,json]
----
{"products":
    {"Red Hat Enterprise Linux":
        {"versions":
            {"7":
                {"titles":
                    {"Developer Guide":
                     {"tests":
                      {"preview":
                       {"job-name":
                        "doc-Red_Hat_Enterprise_Linux-7-Developer_Guide-en-US (test-preview)",
                        "disabled":false,
                        "book-name":"Developer Guide",
                        "job-status":"failure",
                        "product":"Red Hat Enterprise Linux",
                        "environment":"preview",
                        "version":"7",
                        "message":null,
                        "results":null},
                       "stage":
                       {"job-name":
                        "doc-Red_Hat_Enterprise_Linux-7-Developer_Guide-en-US (test-stage)",
                        "disabled":false,
                        "book-name":"Developer Guide",
                        "job-status":"failure",
                        "product":"Red Hat Enterprise Linux",
                        "environment":"stage",
                        "version":"7",
                        "message":null,
                        "results":null},
                       "prod":null}
                      }
                     }
                },
             "6":
                {"titles":
                    {"Security Guide":
                     {"tests":
                      {"preview":
                       {"job-name":
                        "doc-Red_Hat_Enterprise_Linux-6-Security_Guide-en-US (test-preview)",
                        "disabled":false,
                        "book-name":"Security Guide",
                        "job-status":"unstable",
                        "product":"Red Hat Enterprise Linux",
                        "environment":"preview",
                        "version":"6",
                        "message":null,
                        "results":null},
                       "stage":
                       {"job-name":
                        "doc-Red_Hat_Enterprise_Linux-6-Security_Guide-en-US (test-stage)",
                        "disabled":false,
                        "book-name":"Security Guide",
                        "job-status":"unstable",
                        "product":"Red Hat Enterprise Linux",
                        "environment":"stage",
                        "version":"6",
                        "message":null,
                        "results":null},
                       "prod":
                       {"job-name":
                        "doc-Red_Hat_Enterprise_Linux-6-Security_Guide-en-US (test-prod)",
                        "disabled":false,
                        "book-name":"Security Guide",
                        "job-status":"unstable",
                        "product":"Red Hat Enterprise Linux",
                        "environment":"prod",
                        "version":"6",
                        "message":null,
                        "results":null}
                       }
                      }
                     }
                 }
             }
         }
     }
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+



Get job results
~~~~~~~~~~~~~~~

    /api/get_job_results/{JOB_NAME}

Method: +GET+

Content-Type: +application/json+

Response:

[source,json]
----
{
    "metadata" : {
        "name":"doc-book-name (test)"
    },
    "results" : {
        "FirstTest": {
            "testCase#1": [
                {
                    "status":  "info",
                    "message": "xxx"
                }
            ],
            "testCase#2": [
                {
                    "status":  "info",
                    "message": "ACLRef.xml"
                },
                {
                    "status":  "info",
                    "message": "Administration_Guide.xml"
                }
            ]
        }
    }
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Red_Hat_Certificate_System-10.0-Administration_Guide-en-US (test)",
    "command"  : "get_job_results",
    "message"  : "Job does not exist"
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Red_Hat_Certificate_System-10.0-Administration_Guide-en-US (test)",
    "command"  : "get_job_results",
    "message"  : "can not read test results"
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Start job
~~~~~~~~~

    /api/start_job

Starts a Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

Response:

[source,json]
----
{
    "status"   : "ok",
    "job-name" : "doc-Red_Hat_Certificate_System-10.0-Administration_Guide-en-US (test)",
    "command"  : "build",
    "jenkins-response":{"status":302...}}
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "start",
    "message"  : "Job does not exist"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Enable job
~~~~~~~~~~

    /api/enable_job

Enables a Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

Response:

[source,json]
----
{
    "status"   : "ok",
    "job-name" : "doc-Red_Hat_Certificate_System-10.0-Administration_Guide-en-US (test)",
    "command"  : "enable",
    "jenkins-response":{"status":302...}}
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "enable",
    "message"  : "Job does not exist"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Disable job
~~~~~~~~~~~

    /api/disable_job

Disables a Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

Response:

[source,json]
----
{
    "status"   : "ok",
    "job-name" : "doc-Red_Hat_Certificate_System-10.0-Administration_Guide-en-US (test)",
    "command"  : "disable",
    "jenkins-response":{"status":302...}}
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+

Response when error occurs:

[source,json]
----
{
    "status"   : "error",
    "job-name" : "doc-Test_Product-1.0-Test_Book-en-US (test)",
    "command"  : "disable",
    "message"  : "Job does not exist"}
}
----

HTTP Status Code:
+HTTP/1.1 400 Bad Request+



Job started
~~~~~~~~~~~

    /api/job_started

To be called by Emender when the job is started.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+



Job finished
~~~~~~~~~~~~

    /api/job_finished

To be called by Emender when the job is finished.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+


Job results
~~~~~~~~~~~

    /api/job_results

To be called by Emender with the job data.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "metadata" : {
        "name":"doc-Red_Hat_Enterprise_Linux-6-Deployment_Guide (test)"
    },
    "results" : {
        "Test1": {
            "testA": [
                {
                    "status":  "pass",
                    "message": "The function Test1.testA() is called properly."
                }
            ],
            "testB": [
                {
                    "status":  "pass",
                    "message": "The function Test1.testB() is called properly."
                }
            ],
            "testCallOtherFunction": [
                {
                    "status":  "pass",
                    "message": "The function Test1.xyzzy() is called from another function."
                }
            ],
            "testReadLocalValue": [
                {
                    "status":  "pass",
                    "message": "Local variable bind to the test has the value 42"
                }
            ],
            "testReadWriteLocalValue": [
                {
                    "status":  "pass",
                    "message": "Old value is properly set to 42"
                },
                {
                    "status":  "pass",
                    "message": "New value is properly set to 42"
                }
            ]
        },
        "Test2": {
            "testA": [
                {
                    "status":  "pass",
                    "message": "The function Test2.testA() is called properly."
                }
            ],
            "testB": [
                {
                    "status":  "pass",
                    "message": "The function Test2.testB() is called properly."
                }
            ],
            "testCallOtherFunction": [
                {
                    "status":  "pass",
                    "message": "The function Test2.xyzzy() is called from another function."
                }
            ],
            "testReadLocalValue": [
                {
                    "status":  "pass",
                    "message": "Local variable bind to the test has the value 42"
                }
            ],
            "testReadWriteLocalValue": [
                {
                    "status":  "pass",
                    "message": "Old value is properly set to 42"
                },
                {
                    "status":  "pass",
                    "message": "New value is properly set to 42"
                }
            ]
        }
    }
}
----

HTTP Status Code:
+HTTP/1.1 200 OK+



Reload all results
~~~~~~~~~~~~~~~~~~

    /api/reload-all-results

Force to reload all results.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
}

----

HTTP Status Code:
+HTTP/1.1 200 OK+

