REST API for Emender-Jenkins interface
======================================
:icons: font
Pavel Tišnovský <ptisnovs@redhat.com>
v1.0, 2016-06-15

Emender-Jenkins Interface is controlled exclusively via REST API.
Basic supported operations:

Jobs CRUD:

* create new job (that calls Emender)
* read job config
* update job (reconfigure)
* delete job

Other job-related calls:

* start job
* enable job
* disable job
* get list of all jobs
* get job results

Other calls:

* get info about the application
* get banner


REST API calls
--------------



Info
~~~~

    /api

Gets information about the app, such as the version currently running.

Method: +GET+

Content-Type: +application/json+

Example: +curl http://url-to-interface:port/api+

Response:

[source,json]
----
{
    "name" : "Emender Jenkins Service",
    "version" : "0.1.0",
    "api_prefix" : "/api",
    "hostname" : "hostname"
}
----



Banner
~~~~~~

    api/system/banners

Gets the banners that should be displayed in the UI.

Method: +GET+

Content­Type: +application/json+

Example: +curl http://url-to-interface:port/api/system/banners+

Response:

[source,json]
----
[ 
    { 
        "message": "Alpha version",
        "type": "warning" 
    } 
] 
----



Create new job
~~~~~~~~~~~~~~

    /api/create_job

Creates new jenkins job

Method: +POST+

Content­Type: +application/json+

Post Data: 

[source,json]
----
{
    "url_to_repo": "git@some:repo.git",
    "name": "jobName (test)",
    "branch": "preview",
    "metadata": {
        "product": "product name",
        "version": "product version",
        "language": "en­US",
        "environment": "preview",
        "content_directory": "Book directory",
        "content_type": "book"
    } 
} 
----

Response:

[source,json]
----
{
    "data": { 
        "name": "jobName (test)"
    },
    "result": "jenkins job foobar has been created"
}
----



Delete job
~~~~~~~~~~

    /api/delete_job

Deletes an existing Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----



Get job
~~~~~~~

    /api/get_job/{JOB_NAME}

Method: +GET+

Content-Type: +application/json+



Update job
~~~~~~~~~~
    /api/update_job

Updates an existing Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "url_to_repo": "git@some:repo.git",
    "name": "jobName (test)",
    "branch": "preview",
    "metadata": {
        "product": "product name",
        "version": "product version",
        "language": "en­US",
        "environment": "preview",
        "content_directory": "Book directory",
        "content_type": "book"
    } 
}
----



Get jobs
~~~~~~~~

    /api/get_jobs

Method: +GET+

Content-Type: +application/json+



Get job results
~~~~~~~~~~~~~~~

    /api/get_job_results

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----



Start job
~~~~~~~~~

    /api/start_job

Starts a Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----



Enable job
~~~~~~~~~~

    /api/enable_job

Enables a Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----



Disable job
~~~~~~~~~~~

    /api/disable_job

Disables a Jenkins job.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----

Job started
~~~~~~~~~~~

    /api/job_started

To be called by Emender when the job is started.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----


Job finished
~~~~~~~~~~~~

    /api/job_finished

To be called by Emender when the job is finished.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "name": "job-name"
}
----


Job results
~~~~~~~~~~~~

    /api/job_results

To be called by Emender with the job data.

Method: +POST+

Content-Type: +application/json+

Post Data: 

[source,json]
----
{
    "metadata" : {
        "name":"doc-Red_Hat_Enterprise_Linux-6-Deployment_Guide (test)"
    },
    "results" : {
        "Test1": {
            "testA": [
                {
                    "status":  "pass",
                    "message": "The function Test1.testA() is called properly."
                }
            ],
            "testB": [
                {
                    "status":  "pass",
                    "message": "The function Test1.testB() is called properly."
                }
            ],
            "testCallOtherFunction": [
                {
                    "status":  "pass",
                    "message": "The function Test1.xyzzy() is called from another function."
                }
            ],
            "testReadLocalValue": [
                {
                    "status":  "pass",
                    "message": "Local variable bind to the test has the value 42"
                }
            ],
            "testReadWriteLocalValue": [
                {
                    "status":  "pass",
                    "message": "Old value is properly set to 42"
                },
                {
                    "status":  "pass",
                    "message": "New value is properly set to 42"
                }
            ]
        },
        "Test2": {
            "testA": [
                {
                    "status":  "pass",
                    "message": "The function Test2.testA() is called properly."
                }
            ],
            "testB": [
                {
                    "status":  "pass",
                    "message": "The function Test2.testB() is called properly."
                }
            ],
            "testCallOtherFunction": [
                {
                    "status":  "pass",
                    "message": "The function Test2.xyzzy() is called from another function."
                }
            ],
            "testReadLocalValue": [
                {
                    "status":  "pass",
                    "message": "Local variable bind to the test has the value 42"
                }
            ],
            "testReadWriteLocalValue": [
                {
                    "status":  "pass",
                    "message": "Old value is properly set to 42"
                },
                {
                    "status":  "pass",
                    "message": "New value is properly set to 42"
                }
            ]
        }
    }
}

----

